config/routes.rb
MacleansParser::Application.routes.draw do
  resources :publications

  get "pages/home"

  resources :web_issues do
    collection do 
      put 'xml_rpc', path: ':id/xml-rpc'
    end
  end

  resources :issues do
    collection do 
      get 'html_parse', path: '/html-parse'
    end
  end

  get "parsers/html"
  get "parsers/html_parse"
  get "parsers/html_index"
  get "parsers/wordpress"

  root :to => 'pages#home'

end

app/models/web_issue.rb
class WebIssue < ActiveRecord::Base
  attr_accessible :name, :publication, :asset
  attr_accessor :wordpress_url, :login_name, :access_pw
  has_attached_file :asset, :default_url => "/public/issue/:name/:name.zip"
  validates :name, presence: true, uniqueness: true
  validates :publication, presence: true
  validates :asset, presence: true
end

app/controllers/web_issues_controller.rb
class WebIssuesController < ApplicationController
  # GET /web_issues
  # GET /web_issues.json
  def index
    @web_issues = WebIssue.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @web_issues }
    end
  end

  # GET /web_issues/1
  # GET /web_issues/1.json
  def show
    @web_issue = WebIssue.find(params[:id])
    @publications = Publication.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @web_issue }
    end
  end

  def xml_rpc
    @web_issue = WebIssue.find(params[:id])
    WebParser.unzip_file(Dir.glob('public' + @web_issue.asset.url.split('?')[0]).first, 'public/web-issue')
    WebParser.xml_rpc(@web_issue.publication, @web_issue.asset.url.split("/").last.split(".").first, params[:wordpress_url], params[:login_name], params[:access_pw])
    redirect_to @web_issue, notice: 'Web issue was successfully created.'
  end

  # GET /web_issues/new
  # GET /web_issues/new.json
  def new
    @web_issue = WebIssue.new
    @publications = Publication.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @web_issue }
    end
  end

  # GET /web_issues/1/edit
  def edit
    @web_issue = WebIssue.find(params[:id])
  end

  # POST /web_issues
  # POST /web_issues.json
  def create
    @web_issue = WebIssue.new(params[:web_issue])

    if @web_issue.save 
      redirect_to @web_issue, notice: 'Web issue was successfully created.'
    else
      render action: "new"
    end
    
  end

  # PUT /web_issues/1
  # PUT /web_issues/1.json
  def update
    @web_issue = WebIssue.find(params[:id])

    respond_to do |format|
      if @web_issue.update_attributes(params[:web_issue])
        format.html { redirect_to @web_issue, notice: 'Web issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @web_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_issues/1
  # DELETE /web_issues/1.json
  def destroy
    @web_issue = WebIssue.find(params[:id])
    @web_issue.destroy

    respond_to do |format|
      format.html { redirect_to web_issues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/web_issues_helper.rb
module WebIssuesHelper
end

app/views/web_issues/_form.html.erb
<%= form_for(@web_issue) do |f| %>
  <% if @web_issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web_issue.errors.count, "error") %> prohibited this web_issue from being saved:</h2>

      <ul>
      <% @web_issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :publication %><br />
    <%= f.select(:publication, 
        options_from_collection_for_select(@publications, 'abbreviation', 'name')) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :asset %><br />
    <%= f.file_field :asset %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web_issues/edit.html.erb
<h1>Editing web_issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @web_issue %> |
<%= link_to 'Back', web_issues_path %>

app/views/web_issues/index.html.erb
<h1>Wordpress issues</h1>

<table>
  <tr>
    <th>Publication</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @web_issues.each do |web_issue| %>
  <tr>
    <td><%= web_issue.publication %></td>
    <td><%= web_issue.name %></td>
    <td><%= link_to 'Show', web_issue %></td>
    <td><%= link_to 'Edit', edit_web_issue_path(web_issue) %></td>
    <td><%= link_to 'Destroy', web_issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Web issue', new_web_issue_path %>

app/views/web_issues/new.html.erb
<h1>Maclean's Wordpress upload</h1>

<%= render 'form' %>

<%= link_to 'Back', web_issues_path %>

app/views/web_issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Publication:</b>
  <%= @web_issue.publication %>
</p>

<p>
  <b>Name:</b>
  <%= @web_issue.name %>
</p>

<p>
	<%= link_to 'Issue XML archive', @web_issue.asset.url %>
</p>
<%= form_for @web_issue, :url => { :action => 'xml_rpc', :id => @web_issue.id }, :id => 'xml_rpc' do |f| %>
<div class="field">
URL<br />
    <%= select_tag(:wordpress_url, 
        options_from_collection_for_select(@publications, 'url', 'url')) %>
</div>
<div class="field">
Login<br />
<%= text_field_tag :login_name %>
</div>
<div class="field">
PW<br />
<%= password_field_tag :access_pw %>
</div>
<div class='field'>
<%= hidden_field_tag :id, @web_issue.id %>
</div>
<div class="actions">
    <%= f.submit 'Add stories to wordpress' %>
  </div>
<% end %>


<%= link_to 'Edit', edit_web_issue_path(@web_issue) %> |
<%= link_to 'Back', web_issues_path %>