config/routes.rb
MacleansParser::Application.routes.draw do
  resources :publications

  get "pages/home"

  resources :web_issues do
    collection do 
      put 'xml_rpc', path: ':id/xml-rpc'
    end
  end

  resources :issues do
    collection do 
      get 'html_parse', path: '/html-parse'
    end
  end

  get "parsers/html"
  get "parsers/html_parse"
  get "parsers/html_index"
  get "parsers/wordpress"

  root :to => 'pages#home'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :publication, :name, :asset
  has_attached_file :asset, :default_url => "/public/issue/:name/:name.zip"
  validates :name, presence: true, uniqueness: true
  validates :publication, presence: true
  validates :asset, presence: true
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  def html_parse
    @issue = Issue.find(params[:id])
    Parser.unzip_file(Dir.glob('public' + @issue.asset.url.split('?')[0]).first, 'public/issue')
    Parser.html_parse(@issue.asset.url.split("/").last.split(".").first, @issue.publication)
    Parser.zip(@issue.asset.url.split("/").last.split(".").first, @issue.name)
    redirect_to controller: :parsers, action: :html_index
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new
    @publications = Publication.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for @issue, :url => issues_path, :html => { :multipart => true } do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publication %><br />
    <%= f.select(:publication, 
        options_from_collection_for_select(@publications, 'abbreviation', 'name')) %>
  </div>
  <div class="field">
    <%= f.label :issue_number %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :asset %><br />
    <%= f.file_field :asset %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1>iPhone issues</h1>

<table>
  <tr>
    <th>Publication</th>
    <th>Issue #</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= issue.publication %></td>
    <td><%= issue.name %></td>
    <td><%= link_to 'Show', issue %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
    <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>Maclean's iPhone upload</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Publication:</b>
  <%= @issue.publication %>
</p>
<p>
	<b>Issue number:</b>
	<%= @issue.name %>
</p>
<p>
	<%= link_to 'Issue XML archive', @issue.asset.url %>
</p>
<p>
	<%= link_to 'Process XML to HTML', controller: :issues, action: :html_parse, id: @issue.id %>
</p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>