config/routes.rb
MacleansParser::Application.routes.draw do
  resources :publications

  get "pages/home"

  resources :web_issues do
    collection do 
      put 'xml_rpc', path: ':id/xml-rpc'
    end
  end

  resources :issues do
    collection do 
      get 'html_parse', path: '/html-parse'
    end
  end

  get "parsers/html"
  get "parsers/html_parse"
  get "parsers/html_index"
  get "parsers/wordpress"

  root :to => 'pages#home'

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  attr_accessible :abbreviation, :name, :url, :wp_version, :default_author
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publications }
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication = Publication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/new
  # GET /publications/new.json
  def new
    @publication = Publication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render json: @publication, status: :created, location: @publication }
      else
        format.html { render action: "new" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.json
  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.slim
= form_for @publication do |f|
  - if @publication.errors.any?
    #error_explanation
      h2 = "#{pluralize(@publication.errors.count, "error")} prohibited this publication from being saved:"
      ul
        - @publication.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :abbreviation
    = f.text_field :abbreviation
  .field
    = f.label :wp_version
    = f.text_field :wp_version
  .field
    = f.label :default_author
    = f.text_field :default_author
  .field
    = f.label :url
    = f.text_field :url
  .actions = f.submit 'Save'

app/views/publications/edit.html.slim
h1 Editing publication

== render 'form'

= link_to 'Show', @publication
'|
= link_to 'Back', publications_path

app/views/publications/index.html.slim
h1 Listing publications

table
  tr
    th Name
    th Abbreviation
    th Url
    th Wordpress version
    th Default author
    th 
    th
    th

  - @publications.each do |publication|
    tr
      td = publication.name
      td = publication.abbreviation
      td = publication.url
      td = publication.wp_version
      td = publication.default_author
      td = link_to 'Show', publication
      td = link_to 'Edit', edit_publication_path(publication)
      td = link_to 'Destroy', publication, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Publication', new_publication_path

app/views/publications/new.html.slim
h1 New publication

== render 'form'

= link_to 'Back', publications_path

app/views/publications/show.html.slim
p#notice = notice

p
  strong Name:
  = @publication.name
p
  strong Abbreviation:
  = @publication.abbreviation
p
  strong Url:
  = @publication.url
p
  strong Wordpress Version:
  = @publication.wp_version
p
  strong Default author:
  = @publication.default_author

= link_to 'Edit', edit_publication_path(@publication)
'|
= link_to 'Back', publications_path